# Escape Mission Map Objects
# Spawn points and escape routes for the escape scenario

spawns:
  # Player spawn points - start in bottom left
  - name: "Leader Start"
    team: PLAYER
    pos: [1, 8]
    
  - name: "Ally 1 Start"
    team: PLAYER
    pos: [2, 9]
    
  - name: "Ally 2 Start"
    team: PLAYER
    pos: [1, 9]

  # Enemy spawn points - guards blocking the path
  - name: "Guard Post 1"
    team: ENEMY
    pos: [5, 7]
    
  - name: "Guard Post 2"
    team: ENEMY
    pos: [8, 5]
    
  - name: "Guard Post 3"
    team: ENEMY
    pos: [10, 2]
    
  - name: "Patrol 1"
    team: ENEMY
    pos: [6, 4]
    
  - name: "Patrol 2"
    team: ENEMY
    pos: [11, 6]

  # Enemy reinforcement spawn points
  - name: "Reinforcement South"
    team: ENEMY
    pos: [3, 9]
    
  - name: "Reinforcement West"
    team: ENEMY
    pos: [0, 5]

regions:
  # Starting prison area
  - name: "Prison Cells"
    rect: [0, 7, 3, 3]
    description: "Starting position - need to escape quickly!"

  # Escape zone - goal area
  - name: "Escape Zone"
    rect: [12, 0, 3, 3]
    description: "Reach here to escape!"
    defense_bonus: -1  # Exposed position

  # Forest areas provide cover
  - name: "Forest Cover 1"
    rect: [3, 3, 3, 3]
    defense_bonus: 1
    avoid_bonus: 20
    description: "Trees provide cover"
    
  - name: "Forest Cover 2"
    rect: [9, 4, 2, 3]
    defense_bonus: 1
    avoid_bonus: 20
    description: "Trees provide cover"

  # Open roads are dangerous
  - name: "Main Road"
    rect: [4, 0, 2, 10]
    defense_bonus: -1
    description: "Exposed position on the road"
    
  - name: "East Road"
    rect: [6, 2, 6, 2]
    defense_bonus: -1
    description: "Exposed position on the road"

triggers:
  # Victory trigger when units reach escape zone
  - name: "Escape Point"
    type: "enter_region"
    region: "Escape Zone"
    condition: "unit_name:Elara Swiftwind"
    action: "escape_unit"
    data:
      victory_on_escape: true
      
  # Reinforcement triggers
  - name: "Southern Reinforcements"
    type: "turn_start"
    condition: "turn:3"
    action: "spawn_unit"
    data:
      spawn_point: "Reinforcement South"
      unit_class: "WARRIOR"
      
  - name: "Western Reinforcements"
    type: "turn_start"
    condition: "turn:5"
    action: "spawn_unit"
    data:
      spawn_point: "Reinforcement West"
      unit_class: "KNIGHT"
      
  # Warning triggers
  - name: "Road Warning"
    type: "enter_region"
    region: "Main Road"
    condition: "unit_team:PLAYER"
    action: "display_message"
    data:
      message: "Careful! You're exposed on the road!"