# Fortress Defense Map Objects
# Spawn points and strategic regions for fortress defense scenario

spawns:
  # Player spawn points - defenders inside fortress
  - name: "Knight Position"
    team: PLAYER
    pos: [7, 5]
    
  - name: "Archer Position 1"
    team: PLAYER
    pos: [5, 3]
    
  - name: "Archer Position 2"
    team: PLAYER
    pos: [9, 3]
    
  - name: "Cleric Position"
    team: PLAYER
    pos: [7, 3]

  # Enemy spawn points - attackers outside fortress
  - name: "Enemy Knight 1"
    team: ENEMY
    pos: [2, 10]
    
  - name: "Enemy Knight 2"
    team: ENEMY
    pos: [12, 10]
    
  - name: "Enemy Warrior 1"
    team: ENEMY
    pos: [4, 11]
    
  - name: "Enemy Warrior 2"
    team: ENEMY
    pos: [10, 11]
    
  - name: "Enemy Warrior 3"
    team: ENEMY
    pos: [7, 12]
    
  - name: "Enemy Archer"
    team: ENEMY
    pos: [7, 11]

regions:
  # Fortress interior - strong defensive position
  - name: "Fortress Keep"
    rect: [5, 2, 5, 4]  # Central fortress area
    defense_bonus: 3
    avoid_bonus: 10
    description: "The fortress provides excellent defense"

  # Fortress walls provide some defense
  - name: "Fortress Walls"
    rect: [4, 1, 7, 6]  # Outer fortress perimeter
    defense_bonus: 2
    description: "Defensive walls of the fortress"

  # Chokepoints at fortress entrance
  - name: "North Gate"
    rect: [6, 6, 3, 2]
    defense_bonus: 1
    description: "Main entrance to the fortress"

  # Open ground outside - no bonuses
  - name: "Battlefield"
    rect: [0, 8, 15, 5]
    description: "Open ground with no cover"

triggers:
  # Healing point inside fortress
  - name: "Healing Fountain"
    type: "turn_start"
    pos: [7, 3]
    action: "heal_unit"
    data:
      heal_amount: 2
      team: PLAYER
      
  # Warning when enemies breach the walls
  - name: "Breach Warning"
    type: "enter_region"
    region: "Fortress Walls"
    condition: "unit_team:ENEMY"
    action: "display_message"
    data:
      message: "Enemy has breached the fortress walls!"