# Tutorial Map Objects
# Defines spawn points, regions, and triggers for the tutorial map

spawns:
  # Player spawn points
  - name: "Player Start"
    team: PLAYER
    pos: [1, 2]
    class: KNIGHT  # Default class for tutorial

  # Enemy spawn points  
  - name: "Enemy Start"
    team: ENEMY
    pos: [6, 2]
    class: WARRIOR  # Training dummy

regions:
  # Starting area provides defensive bonus
  - name: "Starting Fort"
    rect: [0, 1, 3, 3]  # x, y, width, height
    defense_bonus: 2
    description: "A defensive position for the player"

  # Combat area - neutral ground
  - name: "Battle Ground"
    rect: [3, 1, 3, 3]
    description: "The main combat area"

triggers:
  # Victory trigger when entering enemy start position
  - name: "Victory Zone"
    type: "enter_region"
    region: "Battle Ground"
    condition: "all_enemies_defeated"
    action: "display_message"
    data:
      message: "Tutorial Complete! You've mastered the basics of combat."